module FrontEndAPP
{
   interface FrontEnd
   {
    	string addItem(in string managerID, in string itemID, in string itemName, in long quantity);
		string removeItem(in string managerID, in string itemID, in long quantity);
		string listItemAvailability(in string managerID);
		string borrowItem(in string userID, in string itemID);
		string findItem(in string userID, in string itemName);
		string returnItem(in string userID, in string itemID);
		string checkBorrowList(in string userID);
		string checkWaitList(in string itemID);
		string addToWaitlist(in string userID, in string itemID);
		string exchange(in string studentID, in string newItemID, in string oldItemID);
		string addToWaitlistforExchange(in string studentID, in string newItemID, in string oldItemID);
    	oneway void shutdown();
    };
    
};
 