package FrontEndAPP;

/**
* FrontEndAPP/FrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/chy/eclipse-workspace/DLMS_project/FrontEnd.idl
* Tuesday, March 19, 2019 11:51:58 o'clock PM EDT
*/

public final class FrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndAPP.FrontEnd value = null;

  public FrontEndHolder ()
  {
  }

  public FrontEndHolder (FrontEndAPP.FrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndAPP.FrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndAPP.FrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndAPP.FrontEndHelper.type ();
  }

}
