package FrontEndAPP;


/**
* FrontEndAPP/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/chy/eclipse-workspace/DLMS_project/FrontEnd.idl
* Tuesday, March 19, 2019 5:35:36 o'clock PM EDT
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
